### ISSUE TITLE
What is the use case? More documentation.

### ISSUE THREAD

**Issue by ghost** [watilde/npmbrew#14]
Nice project, but let me clarify a few things by playing devil's advocate here.

The title suggest this is a version manager for `npm`, but as I understand:

> The npm command-line tool is **bundled** with Node.js, so if you already have Node.js installed then you have **npm** too.

So, is this a `node` version manager?

I use [`nvm`](https://github.com/creationix/nvm) to manage multiple node versions [across Linux servers](https://github.com/creationix/nvm/issues/682) as well as compiling `node` from source, as it makes my life easier and I don't have to poke around to see the idiomatic (best way) to `yum` or `apt` get node compatible binaries for a specific platform.

Can you clone and compile from source with `npmbrew`?

**Comment by watilde** [comment]
Thanks for your comment. Truly, npmbrew is a version manager for **npm**. There are two reasons why I made.
1. This is right, but bundled npm version never update **automatically**.
   
   > The npm command-line tool is bundled with Node.js, so if you already have Node.js installed then you have npm too.
2. As far as I've seen (only for a month), the cause of many of the Issue in npm seems that version was too old:
   https://github.com/npm/npm/issues?q=is%3Aissue+is%3Aclosed

So I thought the following feature as a solution:
- You can notice if you are using an older version.
- You can switched to the new version easily.

That's npmbrew.

**Comment by watilde** [comment]
Anyway, I got to know that I have to write more docs to readme... Thanks!

**Comment by ghost** [comment]
:+1: Gotcha.
