### ISSUE TITLE
Rename to npmenv

### ISSUE THREAD

**Issue by ghost** [watilde/npmbrew#16]
What do you think?

Although this is structurally and implemention-wise different from `pyenv` and `rbenv`, it is, after all, a version manager.

EDIT: `npmenv` is not available, but npmvm is.

**Comment by watilde** [comment]
Thanks for your proposal. Rename is a really hard work, so I decided to not do that in this time. Cheers!

**Comment by ghost** [comment]
Really? If you want you can let me do 90 percent and you just unpublish and then reーpublish with the new name. Just let me know.
